server:
  port: 8120 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名

aliyun:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    keyId: LTAI4GF66bfPkA4MPs8Q8v8e
    keySecret: nKeC95McrMe5e4oB53juREcESJrpcZ
    #bucket可以在控制台创建，也可以使用java代码创建，注意先测试bucket是否已被占用
    bucketName: gmall-parent